# Generated by Django 4.1.7 on 2023-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('hard', 'Сложный'), ('medium', 'Средний')], max_length=6),
        ),
    ]
